### PR TITLE
Remove **.py requirement

### PR DESCRIPTION
**Pull request by KoalaGeo**
# Overview

Remove **.py requirement on Lint job run - would wantto run in more conditions as Build & Test jobs are dependant on Lint completing

# Contributions and Licensing

(as per https://github.com/geopython/pygeoapi/blob/master/CONTRIBUTING.md#contributions-and-licensing)

- [x] I'd like to contribute [feature X|bugfix Y|docs|something else] to pygeoapi. I confirm that my contributions to pygeoapi will be compatible with the pygeoapi license guidelines at the time of contribution.
- [x] I have already previously agreed to the pygeoapi Contributions and Licensing Guidelines

### CODE REVIEW

**Comment by tomkralidis** [comment]
@KoalaGeo does this disable CI somehow? I don't see any GitHub Action checks in this PR.

**Comment by KoalaGeo** [comment]
> @KoalaGeo does this disable CI somehow? I don't see any GitHub Action checks in this PR.

Think the last commit has fixed this.

**Comment by tomkralidis** [comment]
Thanks.  I still see PyTorch in the setup?

**Comment by KoalaGeo** [comment]
Ah yes, that looked to be left in from the example yml, now renamed to pygeoapi

**Pull request merged**
