### PR TITLE
Pin starlette version

### PR DESCRIPTION
**Pull request by webb-ben**
# Overview
Pin starlette version to pass CI tests

# Related Issue / Discussion

# Additional Information

# Contributions and Licensing

(as per https://github.com/geopython/pygeoapi/blob/master/CONTRIBUTING.md#contributions-and-licensing)

- [x] I'd like to contribute [feature X|bugfix Y|docs|something else] to pygeoapi. I confirm that my contributions to pygeoapi will be compatible with the pygeoapi license guidelines at the time of contribution.
- [x] I have already previously agreed to the pygeoapi Contributions and Licensing Guidelines

### CODE REVIEW

**Review by francbartoli — COMMENTED** [review]
Hi @webb-ben, may I ask what's the reason to pin it at a specific version?

**Comment by webb-ben** [comment]
@francbartoli Master CI & all CI fails due to a response from the starlette section of test_api.py. Documented at https://github.com/geopython/pygeoapi/issues/1445

**Comment by ricardogsilva** [comment]
@webb-ben @francbartoli see #1447 for an alternative that focuses on modifying the failing tests instead of pinning starletted - there also a relevant comment on #1445

**Comment by webb-ben** [comment]
Thanks @ricardogsilva

**Pull request closed without merging**
