### PR TITLE
1600 allow providing default value in config

### PR DESCRIPTION
**Pull request by ricardogsilva**
# Overview

This PR implements allowing default values for config variables that can come from the environment. Most notably it becomes possible to combine several env variables in a single config value. 

For the most common case of having the full variable correspond to some env value or else a default value, the syntax is `myvar: ${MY_VAR:-some default}`, as shown below:

```yaml
server:
    host: ${MY_HOST:-localhost}
    port: ${MY_PORT:-5000}
    combined: ${MY_HOST:-localhost} - ${MY_PORT:-5000}
```

**UPDATE:** With the latest commit, this paragraph below is no longer relevant - no need to use the `!env` YAML tag

~~For cases where the env variable is being used as part of a config variable and it shows up in the middle of the variable it becomes mandatory to use the `!env` YAML tag:~~

<strike>

```yaml
metadata:
    identification:
        title:
            en: !env This is pygeoapi host ${MY_HOST} and port ${MY_PORT:-5000}, nice to meet you!
```

</strike>

# Related Issue / discussion

- #1600 

# Dependency policy (RFC2)

- [x] I have ensured that this PR meets [RFC2](https://pygeoapi.io/development/rfc/2) requirements

# Updates to public demo

- [x] I have ensured that breaking changes to the [pygeoapi master demo server](https://github.com/geopython/demo.pygeoapi.io) have been addressed
  - [x] https://github.com/geopython/demo.pygeoapi.io/blob/master/services/pygeoapi_master/local.config.yml

# Contributions and licensing

(as per https://github.com/geopython/pygeoapi/blob/master/CONTRIBUTING.md#contributions-and-licensing)

- [x] I'd like to contribute [feature X|bugfix Y|docs|something else] to pygeoapi. I confirm that my contributions to pygeoapi will be compatible with the pygeoapi license guidelines at the time of contribution
- [x] I have already previously agreed to the pygeoapi Contributions and Licensing Guidelines

### CODE REVIEW

**Comment by ricardogsilva** [comment]
Failing CI seems to be due to ubuntugis-ppa being unavailable, it is not related to the changes in this PR, which do not touch any CI or dependency-related things

**Comment by kalxas** [comment]
Launchpad is down for a few hours for maintenance reasons

**Comment by tomkralidis** [comment]
Looks like Launchpad came back.  @ricardogsilva can you check/fix the latest CI failures?

**Comment by ricardogsilva** [comment]
@tomkralidis I'm not able to ask for a re-run of the failed CI workflow - can you please do it?

**Comment by tomkralidis** [comment]
The CI was already re-run, and had some unit test errors.  I've re-run them just now: https://github.com/geopython/pygeoapi/actions/runs/8365396387/job/22911691167?pr=1604#step:20:134

**Comment by ricardogsilva** [comment]
@tomkralidis fixed CI failures

**Pull request merged**
