### PR TITLE
Job submit form improvements

### PR DESCRIPTION
**Pull request by totycro**
These are just 2 minor UI niceties:
* Add an asterisk for mandatory input parameters in the form
* Allow entering float values if the data type is float

### CODE REVIEW

**Comment by alpha-beta-soup** [comment]
Does `step="0.1"` disallowing typing more precise numbers, or does it just control the behaviour of the arrow buttons?

**Comment by totycro** [comment]
It controls the arrow buttons and also validation. So you can input more precise numbers with the keyboard, but they are considered invalid and you can't actually submit a job like this.

I've just learned that there's also `step="any"`, which makes arrow buttons change the value by 1, but allow any manually entered value. What do you think about using that instead?

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/number#step

**Comment by alpha-beta-soup** [comment]
Yeah, that rings a bell. I played around with these but didn't settle on anything, as both of those leave something to be desired. On balance I think it would need to be "any" by default and perhaps open a discussion upstream about how an implementation shuld specifiy input-level precision options for number inputs.

**Comment by tomkralidis** [comment]
Closing given simplification updates i #365

**Pull request closed without merging**
