### PR TITLE
Add Admin API

### PR DESCRIPTION
**Pull request by webb-ben**
# Overview
This PR introduces an OGC API - Features - Part 4 inspired admin API around configuration of pygeoapi resource configurations. It has been implemented and tested for a couple of months as a part of the WMO wis2box OSS software developments efforts in [wis2box-api](https://github.com/wmo-im/wis2box-api). 

@ksonda @tomkralidis Interested to hear what you think about the next steps

Tasks that I am aware still need to be completed:
- [x] Better unit & integration testing for admin API. Might make sense to move the admin api tests to their own CI job.
- [x] conservation of environment variables. 
- [x] deploy the admin CI with a mechanism better than the building the docker example.
- [x] Implementation of corresponding routes with Starlette and Django
- [x] Remove vue from HTML templates
- [x] Create Admin API documentation

# Related Issue / Discussion
https://github.com/geopython/pygeoapi/pull/756, https://github.com/geopython/pygeoapi/issues/728

# Additional Information
Demo deployment exists in the docker examples folder. To Hotload the changes from the API to the configuration, requires changes like that made in the examples entrypoint script.

# Contributions and Licensing

(as per https://github.com/geopython/pygeoapi/blob/master/CONTRIBUTING.md#contributions-and-licensing)

- [x] I'd like to contribute [feature X|bugfix Y|docs|something else] to pygeoapi. I confirm that my contributions to pygeoapi will be compatible with the pygeoapi license guidelines at the time of contribution.
- [x] I have already previously agreed to the pygeoapi Contributions and Licensing Guidelines

### CODE REVIEW

**Comment by webb-ben** [comment]
Updated with some notes additional todos:
[ ] Might make sense to move the admin api tests to their own CI job, and deploy the admin admin with a mechanism better than the building the docker example.
[ ] Create Admin API documentation

**Comment by webb-ben** [comment]
HTML view:
image

**Review by francbartoli — COMMENTED** [review]
Hi @webb-ben, this is a great addition for administrators. However, I was wondering if this Admin API can be made optional for the implementers who want lean and clean OGC APIs without any extra stuff and so do not challenge with security requirements with the introduction of this.

**Comment by tomkralidis** [comment]
It would be valuable to have this configurable in the config.

**Comment by webb-ben** [comment]
> It would be valuable to have this configurable in the config.

@tomkralidis @francbartoli per our previous discussion on this, it is a boolean in the server section:

https://github.com/geopython/pygeoapi/pull/1137/files#diff-631fe735514040ce51f87cfb0c8eeeb1b7895d42c9364cea597355062732c159R466-R467

**Review by francbartoli — CHANGES_REQUESTED** [review]
@webb-ben are `django_admin.py` and `starlette_admin.py` files still missing?

**Comment by webb-ben** [comment]
@francbartoli The admin API has not been implemented for starlette or django - I am new to both of those frameworks.

**Review by francbartoli — CHANGES_REQUESTED** [review]
What would be the benefit to introduce another json related dependency? (I'm asking because we discussed to eventually remove pydantic soon)
Also, since this admin functionality is designed to be optional I wouldn't keep it in the core dependencies. It's better to move it under a `requirements-admin.txt` file

**Comment by tomkralidis** [comment]
@francbartoli the dependency is for JSON merge patching on PUT/PATCH transactions.  Having said this, +1 to move to `requirements-admin.txt`.

**Review by francbartoli — APPROVED** [review]

**Review by tomkralidis — APPROVED** [review]

**Pull request merged**
