### PR TITLE
introduce mini.css

### PR DESCRIPTION
**Pull request by pvgenuchten**
This is a proposal (as a start for #26) to show what a basic css framework can do
[mini.css](https://minicss.org) is one of the common minimal css frameworks out there (License MIT)

image

### CODE REVIEW

**Comment by tomkralidis** [comment]
cc @justb4 (we have a similar situation in [GeoHealthCheck](https://github.com/geopython/GeoHealthCheck))

Thanks @pvgenuchten.  What is the lifecycle of mini.css?  How often should we update it?  This is true of any dependency really but at least our Python deps are one step closer with pip / debian requirements.  How do you see mini.css being maintained over time in pygeoapi?

**Comment by pvgenuchten** [comment]
I'm also new to mini.css also, and neutral to a choice of framework, bootstrap or bulma also fine. mini.css has a bunch of releases, see https://cdnjs.com/libraries/mini.css (47kb). Since i'm not using the advanced features (yet), i guess updates would be limited. Are there any preferences within geopython team? Geonetwork, pycsw.org and ldproxy are bootstrap based (97kb). Both systems use similar naming conventions, eg col-md-6 etc

**Comment by tomkralidis** [comment]
Thanks @pvgenuchten. I'm thinking about upkeep of mini.css in the long term against software (vs. a website).  In GHC part of our setup process includes pulling in JavaScript libs etc.  Should/do we consider this for pygeoapi or keep a static minified copy in version control?

**Comment by pvgenuchten** [comment]
It brings a level of complexity to the build process, but sure can be introduced (at anytime). 

Then include also the leaflet css/javascript (now pulled from unpkg cdn).

**Comment by tomkralidis** [comment]
Good point @pvgenuchten.  Is mini.css available from an unpkg cdn?  If yes, I would suggest we use that approach to be consistent to other js/css deps right now and address these deps as a whole in a separate issue.

**Comment by pvgenuchten** [comment]
now using unpkg for mini.css

**Pull request merged**
