### PR TITLE
Improve gdal package installation

### LINKED ISSUE #619: Force to install a version of the GDAL python bindings aligned with the local binary
**Is your feature request related to a problem? Please describe.**
Improve the user experience during the installation of the providers

### PR DESCRIPTION
**Pull request by francbartoli**
Fix #619

### CODE REVIEW

**Comment by tomkralidis** [comment]
Closing in lieu o #632

**Comment by francbartoli** [comment]
@tomkralidis this PR wasn't unrelated to the Travis failure. Please see #619

**Comment by tomkralidis** [comment]
Oops, sorry!  Reopened.

**Comment by tomkralidis** [comment]
Looks like this is since fixed. Closing.

**Pull request closed without merging**
