### PR TITLE
Update starlette documentation

### PR DESCRIPTION
**Pull request by webb-ben**
# Overview
This PR adds the necessary components to deploy the pygeoapi Docker image with the startlette framework. This can be done by updating two necessary environment variables. Not sure WSGI_APP_FRAMEWORK is the best env variable name seeing as Starlette is ASGI

# Related Issue / Discussion
https://github.com/geopython/pygeoapi/issues/1460, https://github.com/geopython/pygeoapi/issues/1400, https://github.com/geopython/pygeoapi/issues/1111, https://github.com/geopython/pygeoapi/issues/227

# Additional Information

# Contributions and Licensing

(as per https://github.com/geopython/pygeoapi/blob/master/CONTRIBUTING.md#contributions-and-licensing)

- [x] I'd like to contribute [feature X|bugfix Y|docs|something else] to pygeoapi. I confirm that my contributions to pygeoapi will be compatible with the pygeoapi license guidelines at the time of contribution.
- [x] I have already previously agreed to the pygeoapi Contributions and Licensing Guidelines

### CODE REVIEW

**Review by francbartoli — COMMENTED** [review]
Thanks @webb-ben, to be honest with you, if the intent is to provide a ready to go image for production purposes then I really don't understand why we are collapsing two different frameworks into the same image.
Also, as you mentioned starlette is ASGI and so I still really don’t understand why we should scale the workers number within the container rather than doing that at infrastructure level.
I can only understand this addition only if the goal here is to provide a uniform way to make the developer experience easier but I understood in the [#1252](https://github.com/geopython/pygeoapi/pull/1252) this is not the only intent.
Certainly it wouldn’t be the recommended way to deploy other ASGI framework like FastAPI (which is based on Starlette) on containers, k8s or even in serverless functions. In these case I should need a proper Dockerfile to build the optimised image from scratch.
Sorry, I might be wrong, but my feeling is more or less the same as I’ve got with [#1400](https://github.com/geopython/pygeoapi/issues/1400).
I'd like to help here but I don't have any idea other than having different Dockerfiles based on purposes/frameworks. Maybe we could start thinking about a separate `pygeoapi-devops` repository under the Geopython organisation.

**Comment by webb-ben** [comment]
@francbartoli I do not have much experience deploying ASGI. This PR comes from my testing of the Admin API and following the pygeoapi docs on deploying pygeoapi with [gunicorn and starlette](https://docs.pygeoapi.io/en/latest/running.html#gunicorn-and-starlette) which are out of date. 

More than happy to reduce this PR to just fix the documentation if that is the intended purpose. This PR exists in lieu of proper Django and Starlette images for pygeoapi.

**Comment by francbartoli** [comment]
@webb-ben at the same time I don't want to block it, thanks

**Comment by tomkralidis** [comment]
+1 to reduce PR to documentation.  Thanks.

**Comment by webb-ben** [comment]
@tomkralidis ready to merge. Although I am not sure we publish to ghcr anymore.

**Pull request merged**
