### PR TITLE
Publish pygeoapi image to ghcr

### PR DESCRIPTION
**Pull request by webb-ben**
Publish ARM64 and AMD64 versions of pygeoapi to GitHub Container repository with GitHub actions.

### CODE REVIEW

**Review by francbartoli — APPROVED** [review]

**Review by justb4 — CHANGES_REQUESTED** [review]
Thanks for this effort @webb-ben ! You were aware of #866 I think/saw. We all had mainly a lack of time. See [my comments there](https://github.com/geopython/pygeoapi/pull/801#issuecomment-1009739629). As this is IMO quite fundamental to project-Quality, would like to have others in PSC to comment. That is why I added a [message today in the Gitter chat](https://gitter.im/geopython/pygeoapi?at=6229f0766b91242320292e8e) as to not have it hidden in a PR review. Hoping for your understanding and patience!

**Comment by tomkralidis** [comment]
@webb-ben is this PR still valid/needed?  cc @justb4 @KoalaGeo

**Comment by KoalaGeo** [comment]
This functionality is now in https://github.com/geopython/pygeoapi/blob/master/.github/workflows/containers.yml

**Comment by tomkralidis** [comment]
Thanks, closing.

**Pull request closed without merging**
