### PR TITLE
Proposal for enabling property filtering with ogr provider

### PR DESCRIPTION
**Pull request by ynte**
Being able to filter on the properties of ogr data sources is very important for me. So i've developed the following code to add this ability to the provider in question. I can improve upon this pull request and add tests if this feature is something you guys would consider adding.

I did wonder why `get_fields` was not used yet, perhaps there was a problem that prevented the loading of fields?

Using this project to consume legacy api's and expose them through a modern easy to implement protocol sounds very appealing to me, so i would love to help :+1:

### CODE REVIEW

**Comment by justb4** [comment]
Ok, thanks @ynte ! Yes, a very useful feature, give me some time to review (now travelling back from FOSS4G). Yes, preferably add unit tests and try to test with different OGR backends (services like WFS v1/2, GeoJSON etc). `GetFields`, maybe not all OGR backends gave correct results? Have to look into. Property filtering may also be a very expensive operation for big e.g. DB tables where the properties are not indexed...

**Comment by ynte** [comment]
I added tests in the currently defined ogr suites (gpkg, sqlite, wfs, shapefile). I could try to find an ogr format that does not support `SetAttributeFilter`, I think the AttributeFilter would simply be ignored in that case.

It's true property filtering might be very expensive. Perhaps the fields that are available for filtering could be constrained in the configuration of the dataset.

**Comment by justb4** [comment]
Hmm, new insights, see [my comment here, last sentences](https://github.com/geopython/pygeoapi/pull/283#discussion_r337930549). @ynte "your `get_fields()`" made sense after all in your context, but we should solve this in core:

* attempting to populate `self.fields` for any Provider
* checks for allowed `properties` ([already implemented](https://github.com/geopython/pygeoapi/blob/master/pygeoapi/api.py#L574))

**Comment by ynte** [comment]
That is how I remembered it. I wanted to double check it before answering, but hadn't found any time for that yet.

I can imagine the current situation isn't perfect yet. I think an ability to confine the fields that can be filtered on would be very useful for instance. That way admins can prevent filtering on non-indexed fields. But as I understand from your comments that sort of functionality does not belong to the data sources themselves.

**Comment by ynte** [comment]
I tried to merge the upstream master, but I think i have failed 😅. I'll have to come back to this later unfortunately.

**Comment by ynte** [comment]
I'm sorry for the mess :stuck_out_tongue_closed_eyes: , the PR should be clean and up to date now.

**Comment by justb4** [comment]
@ynte no sweat! We're all busy bees, and always happy with contributions! Yes, I tripped in the `flake8` error (one space on empty line is enough) many a time!

**Comment by ynte** [comment]
In reference to #398: what was blocking the inclusion of this PR?

**Comment by justb4** [comment]
> In reference to #398: what was blocking the inclusion of this PR?

Not sure, maybe the API was not ready, concerns with large datasets like WFS, or I overlooked something. I tested just now locally and merged locally without conflicts and tests run ok! See [Gitter](https://gitter.im/geopython/pygeoapi?at=5e9452afcc370f0b07df2ce1). So will merge, thanks for patience @ynte .

**Pull request merged**
