### PR TITLE
Fix docker build

### LINKED ISSUE #387: Docker build is broken due to the gevent version on master
**Description**
Docker build is failing with the installation of gevent python package. The issue can be solved by upgrading the version of gevent

**Steps to Reproduce**

`docker build -t geopython/pygeoapi .`

**Expected behavior**

**Screenshots/Tracebacks**

**Environment**
 - OS:
 - Python version: 
 - pygeoapi version: 

**Additional context**

### PR DESCRIPTION
**Pull request by francbartoli**
Closes #387

### CODE REVIEW

**Comment by francbartoli** [comment]
@justb4 new commit has pinned version

**Comment by justb4** [comment]
Strange, now the Travis build fails: *The command "sudo apt-get install -y postgresql-10-postgis-3" failed and exited with 100 during* *postgresql-10-postgis-3 : Depends: libgdal20 (>= 2.0.1) but it is not going to be installed*

**Comment by francbartoli** [comment]
Strange indeed, trying to reproduce the error in a docker sandbox with no luck. I cannot and also the following query below gives different insight:

```shell
root@b5ee27f16026:/# apt-cache show postgresql-10-postgis-3
Package: postgresql-10-postgis-3
Source: postgis
Priority: optional
Section: misc
Installed-Size: 3183
Maintainer: Debian GIS Project <pkg-grass-devel@lists.alioth.debian.org>
Architecture: amd64
Version: 3.0.1+dfsg-2~bionic0
Suggests: postgis
Provides: postgresql-10-postgis, postgresql-postgis
Depends: postgresql-10, postgresql-10-postgis-3-scripts, libc6 (>= 2.14), libgcc1 (>= 1:3.0), libgdal26 (>= 2.0.1), libgeos-c1v5 (>= 3.8.0), libjson-c3 (>= 0.11), libpcre3, libproj19 (>= 6.0.0), libprotobuf-c1 (>= 1.0.1), libsfcgal1 (>= 1.3.1), libstdc++6 (>= 5), libxml2 (>= 2.7.4)
Breaks: postgis (<< 1.2.1)
Filename: pool/main/p/postgis/postgresql-10-postgis-3_3.0.1+dfsg-2~bionic0_amd64.deb
Size: 868256
MD5sum: 4b3cc779311ee361a2cc18cd0e18aaf9
SHA1: 2cacdc888563e8d99a1360ec72d8b17f2ea1b71a
SHA256: bf19742d2ae045389dc5caad9cdad2148cf0eed2fc85b540d450551bad1ec2eb
Description: Geographic objects support for PostgreSQL 10
Description-md5: cd5594753542ceddde355574daac3832
```

I'll do a try by removing the pin to a version

**Comment by francbartoli** [comment]
No idea, it worked three days ago https://travis-ci.org/github/geopython/pygeoapi/jobs/668040716. Now failing with the same packages, maybe @kalxas has more ideas

**Comment by francbartoli** [comment]
Update:

```shell
# GDAL 3 library installed
travis@d0fa63c09172:~$ sudo apt-get install -y libgdal26
Reading package lists... Done
Building dependency tree
Reading state information... Done
libgdal26 is already the newest version (3.0.4+dfsg-1~bionic0).
libgdal26 set to manually installed.
0 upgraded, 0 newly installed, 0 to remove and 96 not upgraded.
```

```shell
# PostGIS 3 depends on `libgdal26` and not `libgdal20`
travis@d0fa63c09172:~$ sudo apt-cache show postgresql-10-postgis-3
Package: postgresql-10-postgis-3
Source: postgis
Version: 3.0.1+dfsg-2.pgdg18.04+1
Architecture: amd64
Maintainer: Debian GIS Project <pkg-grass-devel@lists.alioth.debian.org>
Installed-Size: 3191
Depends: postgresql-10, postgresql-10-postgis-3-scripts, libc6 (>= 2.14), libgcc1 (>= 1:3.0), libgdal20 (>= 2.0.1), libgeos-c1v5 (>= 3.7.0), libjson-c3 (>= 0.11), libpcre3, libproj12 (>= 4.9.0), libprotobuf-c1 (>= 1.0.1), libsfcgal1 (>= 1.2.0), libstdc++6 (>= 5), libxml2 (>= 2.7.4)
Suggests: postgis
Breaks: postgis (<< 1.2.1)
Provides: postgresql-10-postgis, postgresql-postgis
Homepage: http://postgis.net/
Priority: optional
Section: misc
Filename: pool/main/p/postgis/postgresql-10-postgis-3_3.0.1+dfsg-2.pgdg18.04+1_amd64.deb
Size: 870924
SHA256: e9028242c47fd250d83ff7580f1582280488d292c46a361a14ab46852ff20505
SHA1: a60d6f57ce14e891edeac50c08f57f49415f15bf
MD5sum: a895bbc17ed84495eec493f701301718
Description: Geographic objects support for PostgreSQL 10
 PostGIS adds support for geographic objects to the PostgreSQL
 object-relational database. In effect, PostGIS "spatially enables"
 the PostgreSQL server, allowing it to be used as a backend spatial
 database for geographic information systems (GIS), much like ESRI's
 SDE or Oracle's Spatial extension. PostGIS follows the OpenGIS
 "Simple Features Specification for SQL".
 .
 To create the PostGIS extensions in a PostgreSQL 10 database, the
 postgresql-10-postgis-3-scripts package must be installed as well.
Description-md5: cd5594753542ceddde355574daac3832

Package: postgresql-10-postgis-3
Source: postgis
Priority: optional
Section: misc
Installed-Size: 3183
Maintainer: Debian GIS Project <pkg-grass-devel@lists.alioth.debian.org>
Architecture: amd64
Version: 3.0.1+dfsg-2~bionic0
Suggests: postgis
Provides: postgresql-10-postgis, postgresql-postgis
Depends: postgresql-10, postgresql-10-postgis-3-scripts, libc6 (>= 2.14), libgcc1 (>= 1:3.0), libgdal26 (>= 2.0.1), libgeos-c1v5 (>= 3.8.0), libjson-c3 (>= 0.11), libpcre3, libproj19 (>= 6.0.0), libprotobuf-c1 (>= 1.0.1), libsfcgal1 (>= 1.3.1), libstdc++6 (>= 5), libxml2 (>= 2.7.4)
Breaks: postgis (<< 1.2.1)
Filename: pool/main/p/postgis/postgresql-10-postgis-3_3.0.1+dfsg-2~bionic0_amd64.deb
Size: 868256
MD5sum: 4b3cc779311ee361a2cc18cd0e18aaf9
SHA1: 2cacdc888563e8d99a1360ec72d8b17f2ea1b71a
SHA256: bf19742d2ae045389dc5caad9cdad2148cf0eed2fc85b540d450551bad1ec2eb
Description: Geographic objects support for PostgreSQL 10
 PostGIS adds support for geographic objects to the PostgreSQL
 object-relational database. In effect, PostGIS "spatially enables"
 the PostgreSQL server, allowing it to be used as a backend spatial
 database for geographic information systems (GIS), much like ESRI's
 SDE or Oracle's Spatial extension. PostGIS follows the OpenGIS
 "Simple Features Specification for SQL".
 .
 To create the PostGIS extensions in a PostgreSQL 10 database, the
 postgresql-10-postgis-3-scripts package must be installed as well.
Description-md5: cd5594753542ceddde355574daac3832
```

I don't have any clue about the reason for such an error :(

**Pull request merged**
