### PR TITLE
Closes #257

### LINKED ISSUE #257: [Starlette] Next link for items is broken
**Description**
The link _Next_ from the endpoint `items` returns a `404` status code

**Steps to Reproduce**

1. Start in dev mode `pygeoapi serve --starlette`
2. Open `http://localhost:5000/collections/countries/items` in the browser
3. Click the button _Next_

**Expected behavior**
Open the html page with the next 10 items as it happens when running with the option `--flask`

**Screenshots/Tracebacks**

**Environment**
 - OS: Mac OS X
 - Python version: 3.7.4
 - pygeoapi version: master

**Additional context**

### PR DESCRIPTION
**Pull request by francbartoli**

### CODE REVIEW

**Comment by tomkralidis** [comment]
@francbartoli I tried the following (instead, with `pygeoapi/starlette_app.py` unchanged:

```diff
diff --git a/pygeoapi/api.py b/pygeoapi/api.py
index 232d209..6af4351 100644
--- a/pygeoapi/api.py
+++ b/pygeoapi/api.py
@@ -619,13 +619,13 @@ class API(object):
             'type': 'application/geo+json',
             'rel': 'prev',
             'title': 'items (prev)',
-            'href': '{}/collections/{}/items/?startindex={}'.format(
+            'href': '{}/collections/{}/items?startindex={}'.format(
                 self.config['server']['url'], dataset, prev)
             }, {
             'type': 'application/geo+json',
             'rel': 'next',
             'title': 'items (next)',
-            'href': '{}/collections/{}/items/?startindex={}'.format(
+            'href': '{}/collections/{}/items?startindex={}'.format(
                 self.config['server']['url'], dataset, next_)
             }, {
             'type': 'application/json',
```

This seems to work in both flask and starlette.

Having said this, should we support trailing slashes in our routes?  Or is this left to the web server (i.e. Apache `DirectorySlash`)?

**Comment by francbartoli** [comment]
Thanks @tomkralidis, you are right that change in the button link works indeed. However, I have seen a different behavior from flask to starlette to handling the trailing slash in routes. I guess flask supports it implicitly while starlette doesn't. I'd like to have them aligned but it could be within a different ticket. What do you think?

**Comment by tomkralidis** [comment]
Thanks @francbartoli. +1 to add the pygeoapi/api.py change and to open a other ticket to discuss trailing slashes consistency

**Comment by francbartoli** [comment]
> Thanks @francbartoli. +1 to add the pygeoapi/api.py change and to open a other ticket to discuss trailing slashes consistency

I'm going to close this and open a different PR

**Pull request closed without merging**
