### PR TITLE
#1110 - disable build for test and upgrade action versions

### PR DESCRIPTION
**Pull request by justb4**
# Overview
Disable build for test (test is skipped anyway) and upgrade all Action versions.

# Related Issue / Discussion
Issue #1110

# Additional Information
See discussion [after these comments](https://github.com/geopython/pygeoapi/pull/1093#issuecomment-1387271180) on #1093. We should at least get the Docker build/push working again. Then work on #1105.

# Contributions and Licensing

(as per https://github.com/geopython/pygeoapi/blob/master/CONTRIBUTING.md#contributions-and-licensing)

- [x] I'd like to contribute [feature X|bugfix Y|docs|something else] to pygeoapi. I confirm that my contributions to pygeoapi will be compatible with the pygeoapi license guidelines at the time of contribution.
- [x] I have already previously agreed to the pygeoapi Contributions and Licensing Guidelines

### CODE REVIEW

**Review by francbartoli — APPROVED** [review]

**Comment by justb4** [comment]
The Action for the containers.yml is not run on PR-branches. Only way to test is by merge-push this PR....

**Comment by justb4** [comment]
@francbartoli @tomkralidis it is still stuck in the build. The only way to quickly test is to leave out stuff like ARM build and pushing to GH Docker Repo. It looks like it is waiting for something, but we have no log output from that Workflow step. Will be very long cycles via subsequent PRs. If you allow me to directly push containers.yml to master I can move more quickly. There is no other way to test.

**Comment by justb4** [comment]
I searched on the web and see multiple causes for "Buildx Docker hanging or stuck":

* moving from Focal to Jammy (in build, thus GH Workflow environment), we use ubuntu-latest
* single Layer (RUN) in Docker file could be too big for constrained CI/CD environment

The builds/pushes worked before. Main thing that has changed is our Dockerfile...

The build is locally even quicker, like 3 mins, because of `python3-` packages, no wheel builds. The Image is still 1.2 GB.
From the log-files nothing sensible comes out.

**Comment by justb4** [comment]
What I do see in the log output is that the build hangs on pulling from docker.io. Normally we should see this:

```
#3 [internal] load metadata for docker.io/library/ubuntu:jammy
#3 sha256:5e41972c0cdee05640f3ed85ad5e7dca92c5a589ced43badaf14d81466f891ae
#3 ...

#4 [auth] library/ubuntu:pull token for registry-1.docker.io
#4 sha256:72c043b5df0f56bdba92ea22bd3161e532207e3ed889a37fa862f3467425ef2a
#4 DONE 0.0s

#3 [internal] load metadata for docker.io/library/ubuntu:jammy
#3 sha256:5e41972c0cdee05640f3ed85ad5e7dca92c5a589ced43badaf14d81466f891ae
#3 DONE 4.7s
```
The build is stuck after Step 2, loading the Dockerfile.

**Comment by justb4** [comment]
See also the raw output from GHA:

[raw-output.txt](https://github.com/geopython/pygeoapi/files/10467172/raw-output.txt)

**Pull request merged**
