### PR TITLE
Meta review

### PR DESCRIPTION
**Pull request by alpha-beta-soup**
Includes changes from #465 

Attempts to address:
- #384 (only partially - geometry is mandatorily omitted for GeoJSON-LD payloads with non-point geometry)
- #433 (`uri_field` is obtained from configuration, to support custom URIs for features, which determine JSON-LD `@id` at the level of an individual feature)
- #453 (in the UI, there is now a URI property in item tables, that (by default) links to the Pygeoapi item itself, or to a URI from a property (intended to support PIDs) 
- #457 (inlines the GeoJSON-LD context; addresses problems with https://schema.org ignoring content negotiation and not returning JSON-LD `@context` data)
- #459 (removes schema.org microdata; leaves JSON-LD as the only method of describing embedded meta/data)

I appreciate that this is a lot to pick off in a single merge, but these issues were genuinely quite intertwined, and changes to support the custom ID require careful examination of how the feature IDs are treated in the codebase.

I'd really appreciate if @gpetrochenkov-usgs, @ksonda and @dblodgett-usgs could check out this branch and use it with your sample data to see if it still meets all the requirements you have for linked data support in pygeoapi.

I also took the opportunity to do some refactoring. In particular, all JSON-LD responses are now obtained with the use of the `@jsonldify` function decorator, which inspects function names as strings and does appropriate work. This allows the decorator to either do some pre-computation before the decorated function runs (e.g. to generate `API.fcmld`) or to transform the decorated function output (e.g. to transform GeoJSON data, which may have been filtered, to GeoJSON-LD), or to do a no-op for functions where the appropriate JSON-LD mapping has not been determined (e.g. for STAC).

All tests pass.

### CODE REVIEW

**Comment by ksonda** [comment]
Thanks much @alpha-beta-soup and @gpetrochenkov-usgs !  The docker image internetofwater/pygeoapi-geoconnex:context mod incorporates this PR and an example deployment is at https://wade-test.geoconnex.us Everything appears to behave as we want it to. @dblodgett-usgs can confirm.

**Comment by dblodgett-usgs** [comment]
I am stoked. Thanks everyone. This looks good enough for government work. 

If there's one thing that ended up a little unfortunate it's the repeated uri/id property as in 
https://wade-test.geoconnex.us/collections/WaDE/items/NM_4488?f=jsonld and https://wade-test.geoconnex.us/collections/WaDE/items/NM_4488?f=html

I'm not sure it matters enough to mess with, but figured I'd mention it.

**Comment by ksonda** [comment]
was some version of this ever merged? I cant get the master branch image to have this functionality.

**Comment by alpha-beta-soup** [comment]
No, this is still open and unmerged, and now needs to be updated to work with the current state of master

**Comment by dblodgett-usgs** [comment]
I've asked @gpetrochenkov-usgs to have a look at getting these conflicts resolved. If and when that happens, we should really get this merged if at all possible.

**Comment by tomkralidis** [comment]
Closing given #676

**Pull request closed without merging**
