### PR TITLE
Pin jinja2 to fix buggy version

### LINKED ISSUE #875: Build is currently broken caused by latest jinja2 version
**Description**
Getting this error in our builds since the latest release 3.1.0 of Jinja2.

`module 'jinja2.utils' has no attribute 'escape'`

More insights [here](https://github.com/sphinx-doc/sphinx/issues/10289)

**Steps to Reproduce**
Run a build

**Expected behavior**
Build shouldn't fail

**Screenshots/Tracebacks**

**Environment**
 - OS:
 - Python version:
 - pygeoapi version:

**Additional context**

### PR DESCRIPTION
**Pull request by francbartoli**
Close #875

### CODE REVIEW

**Comment by tomkralidis** [comment]
FYI Jinja2 has since made a bugfix release (3.1.1) which fixes this issue (we ran into this in pygeometa). We should be okay at this point without having to pin.

**Comment by francbartoli** [comment]
> FYI Jinja2 has since made a bugfix release (3.1.1) which fixes this issue (we ran into this in pygeometa). We should be okay at this point without having to pin.

It is still failing for me https://github.com/geopython/pygeoapi/runs/5716551522?check_suite_focus=true

**Comment by jaidisido** [comment]
Failing for me too

**Comment by justb4** [comment]
Think this is due to Flask. Think we use 1.1.2 and that version does not pin jinja2: see
https://github.com/pallets/flask/issues/4494

**Comment by justb4** [comment]
This is how I solved in GeoHealthCheck: https://github.com/geopython/GeoHealthCheck/issues/423 . So pinning these two:

```
Jinja2==2.11.3
markupsafe==2.0.1
```
`markupsafe` is for Sphinx doc but also used by Jinja (or other way around).

**Review by justb4 — COMMENTED** [review]
See my comment: https://github.com/geopython/pygeoapi/pull/876#issuecomment-1080778923 . You may try the same fix: 
```
Jinja2==2.11.3
markupsafe==2.0.1

```

**Comment by francbartoli** [comment]
> See my comment: [#876 (comment)](https://github.com/geopython/pygeoapi/pull/876#issuecomment-1080778923) . You may try the same fix:
> 
> ```
> Jinja2==2.11.3
> markupsafe==2.0.1
> ```

@justb4 your changes would impact over two different requirements files since markupsafe comes from sphinx. Pinning to the latest working version is still safely passing the build. Can we merge as it is?

**Comment by justb4** [comment]
Ok, yes that was the GHC fix, where the docs are part of the app. Ok, whatever pinned version works as @francbartoli [indicated that 3.0.3 fails for him](https://github.com/geopython/pygeoapi/pull/876#issuecomment-1080332841). Maybe thus Jinja2 2.11.3. If the Sphinx build does not fail, no need to fix.

**Comment by webb-ben** [comment]
fwiw this would also address #715 and #796

**Pull request merged**
