### PR TITLE
Add missing distutils for Travis

### PR DESCRIPTION
**Pull request by kalxas**

### CODE REVIEW

**Comment by justb4** [comment]
@kalxas are you aware of issue #585. This PR seems to address that as well. 
I am trying out the Dockerfile now.

**Comment by kalxas** [comment]
I will have a look and provide updates

**Comment by kalxas** [comment]
This mix of pip and debian packages is a recipe for trouble.
I would recommend to only use only debian packages for things that are available.

**Comment by kalxas** [comment]
New PR #598

**Pull request closed without merging**
