### PR TITLE
Describe required collection level metadata about EDR Queries 

### PR DESCRIPTION
**Pull request by webb-ben**
# Overview
Adds the necessary components to decribe EDR collections to work with EDR clients like 
https://labs.metoffice.gov.uk/edr/static/html/query.html

# Related Issue / discussion
https://github.com/geopython/pygeoapi/pull/1151

# Additional information
Demo running on this branch
image

# Dependency policy (RFC2)

- [x] I have ensured that this PR meets [RFC2](https://pygeoapi.io/development/rfc/2) requirements

# Updates to public demo

- [x] I have ensured that breaking changes to the [pygeoapi master demo server](https://github.com/geopython/demo.pygeoapi.io) have been addressed
  - [x] https://github.com/geopython/demo.pygeoapi.io/blob/master/services/pygeoapi_master/local.config.yml

# Contributions and licensing

(as per https://github.com/geopython/pygeoapi/blob/master/CONTRIBUTING.md#contributions-and-licensing)

- [x] I'd like to contribute [feature X|bugfix Y|docs|something else] to pygeoapi. I confirm that my contributions to pygeoapi will be compatible with the pygeoapi license guidelines at the time of contribution
- [x] I have already previously agreed to the pygeoapi Contributions and Licensing Guidelines

### CODE REVIEW

**Comment by tomkralidis** [comment]
Pausing until https://github.com/opengeospatial/ogcapi-environmental-data-retrieval/issues/563 is addressed.

**Comment by webb-ben** [comment]
+1

I am interested in clarifying the `extents.temporal.values` field. It is present in the [EDR spec for temporal extents](https://docs.ogc.org/is/19-086r6/19-086r6.html#_8f4c9f38-bc6a-4b98-8fd9-772e42d60ab2)), but not in the OAF 
image

**Comment by tomkralidis** [comment]
OGC API - Features does not imply a temporal model for collections.  Feature data may or may not have a temporal aspect.

OGC API - Environmental Data Retrieval implies a more specific collection model given the temporal nature of the data it aims to support.

**Comment by webb-ben** [comment]
As written, there is no differentiation between the OGC API - EDR and OGC API - Features temporal configuration. Should EDR collections be validated against https://schemas.opengis.net/ogcapi/edr/1.1/openapi/schemas/collections/extent.yaml?

Or is it fine as implemented in this PR?

**Comment by tomkralidis** [comment]
pygeoapi only validates OpenAPI generation and config (not at runtime). For responses, we create the response as per the specification(s) and leave hard validation to CITE.

**Pull request merged**
