### PR TITLE
Move debian packaging to salsa.debian.org

### PR DESCRIPTION
**Pull request by xamanu**
# Overview

I would like to suggest to move the debian packaging into one place: https://salsa.debian.org/debian-gis-team/pygeoapi/ There the operating system specific packaging is going to be maintained by the Debian GIS Team, and the upstream developers won't have to deal with it.

# Contributions and Licensing

(as per https://github.com/geopython/pygeoapi/blob/master/CONTRIBUTING.md#contributions-and-licensing)

- [x] I'd like to contribute [feature X|bugfix Y|docs|something else] to pygeoapi. I confirm that my contributions to pygeoapi will be compatible with the pygeoapi license guidelines at the time of contribution.
- [ ] I have already previously agreed to the pygeoapi Contributions and Licensing Guidelines

### CODE REVIEW

**Comment by tomkralidis** [comment]
I'll merge this once #1307 is merged.  Note I'm also working on #1302, but am I guessing this PR can be merged just the same, (#1302 will take some time).  Does this make sense @xamanu  @kalxas ?

**Comment by tomkralidis** [comment]
FYI #1307 has been merged.  @xamanu can you fix the resulting merge conflicts?  Thanks.

**Comment by xamanu** [comment]
Rebased on latest master.

**Comment by tomkralidis** [comment]
Thanks @xamanu.  Next step is approval from @kalxas.

**Review by kalxas — APPROVED** [review]

**Pull request merged**
