### PR TITLE
Fix service-doc and service-desc inversion, and update media type of openapi+json

### PR DESCRIPTION
**Pull request by rouault**

### CODE REVIEW

**Comment by justb4** [comment]
@rouault good to see you contributing! FYI: the Travis build failed because of a Python formatting error. `flake8` is quite strict here:

```
./pygeoapi/api.py:211:80: E501 line too long (81 > 79 characters)
```

This also hits us now and then :-(. Best is to install flake8 and run it from topdir before commits/push.

**Comment by rouault** [comment]
>  If you only fix the Python formatting (line length), and have successful Travis build we can merge.

just force pushed with a fix

**Comment by justb4** [comment]
Ok, thanks @rouault !

**Comment by tomkralidis** [comment]
Thanks @rouault !

**Pull request merged**
