### PR TITLE
Refactor code base to make it work with pydantic v2

### PR DESCRIPTION
**Pull request by MTachon**
# Overview
This PR refactor the code using pydantic to make it work with pydantic V2. Originally implemented in PR https://github.com/geopython/pygeoapi/pull/1349, but moved the pydantic related changes to this new PR.

# Related Issue / Discussion
https://github.com/geopython/pygeoapi/pull/1349

# Additional Information
This PR add `typing-extensions` to `requirements.txt` to allow for the use of the `Literal` type. If the python version is update in CI to version 3.8 or above, the `Literal` can be directly imported from the `typing` standard library and `typing-extensions` will not be needed.

# Contributions and Licensing

(as per https://github.com/geopython/pygeoapi/blob/master/CONTRIBUTING.md#contributions-and-licensing)

- [x] I'd like to contribute [feature X|bugfix Y|docs|something else] to pygeoapi. I confirm that my contributions to pygeoapi will be compatible with the pygeoapi license guidelines at the time of contribution.
- [x] I have already previously agreed to the pygeoapi Contributions and Licensing Guidelines

### CODE REVIEW

**Review by francbartoli — APPROVED** [review]

**Comment by ricardogsilva** [comment]
@MTachon 

I'm just coming back to working on pygeoapi after a short break and this was breaking my local dev env because I still have `pydantic 1.10.7` on my local env and it did not get updated when I pip installed stuff.

How about adding a version specifier on `requirements.txt` noting that we explicitly do not support pydantic < v2 anymore?

**Comment by ricardogsilva** [comment]
@MTachon 

furthermore, when I tried to update pydantic, I quickly descended into a rabbit hole, with pip complaining about conflicting version of `datamodel-code-generator`, which led me to try to upgrade it only to be met with another conflict of `imporlib-metadata`, which led to another conflict with `flak8`, which led to another conflict...

I eventually gave up, trashed my previous virtualenv, recreated it and did a fresh install of all requirements.

So please disregard my previous comment :sweat_smile: 

I think we should eventually pin all dependencies to known working versions on the requirements file(s), but it seems like that would be a broader change, not tied up with anything related to this PR

**Comment by ricardogsilva** [comment]
@MTachon 
cc @francbartoli 

Ouch, hold on

On second thought, now I'm noticing my fresh new virtualenv actually has `pydantic v1.10.13`, which is kind of a problem?

I just did:

```shell

# activate python 3.7, the lowest version supported by pygeoapi
pyenv shell 3.7

# create a new empty virtualenv
python -m venv .venv

# activate the virtualenv
source .venv/bin/activate

# upgrade pip
pip install --upgrade pip

# install pygeoapi dependencies
pip install \
    -r requirements.txt \
    -r requirements-dev.txt \
    -r requirements-provider.txt \
    -r requirements-starlette.txt \
    -r requirements-django.txt \
    -r requirements-docker.txt 

# install pygeoapi in editable mode
pip install --editable .
```

everything installed fine.

But now when I try to launch pygeoapi I get an error related to pydantic - basically complaining that I have pydantic v1 and pygeoapi needs pydantic v2

```shell
YGEOAPI_CONFIG=example-config.yml PYGEOAPI_OPENAPI=example-openapi.yml pygeoapi --help
Traceback (most recent call last):
  File "/datadisk/dev/pygeoapi/.venv/bin/pygeoapi", line 11, in <module>
    load_entry_point('pygeoapi', 'console_scripts', 'pygeoapi')()
  File "/datadisk/dev/pygeoapi/.venv/lib/python3.7/site-packages/pkg_resources/__init__.py", line 490, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/datadisk/dev/pygeoapi/.venv/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2862, in load_entry_point
    return ep.load()
  File "/datadisk/dev/pygeoapi/.venv/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2462, in load
    return self.resolve()
  File "/datadisk/dev/pygeoapi/.venv/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2468, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/datadisk/dev/pygeoapi/pygeoapi/__init__.py", line 41, in <module>
    from pygeoapi.openapi import openapi
  File "/datadisk/dev/pygeoapi/pygeoapi/openapi.py", line 47, in <module>
    from pygeoapi.models.openapi import OAPIFormat
  File "/datadisk/dev/pygeoapi/pygeoapi/models/openapi.py", line 34, in <module>
    from pydantic import RootModel
ImportError: cannot import name 'RootModel' from 'pydantic' (/datadisk/dev/pygeoapi/.venv/lib/python3.7/site-packages/pydantic/__init__.cpython-37m-x86_64-linux-gnu.so)
```

Sure enough, the output of `pip freeze` shows pydantic v1 is installed:

```shell
pip freeze | grep pydantic
pydantic==1.10.13
```

Does this mean that it is not possible to get a working pygeoapi installation now? Or am I doing something wrong?

**Comment by francbartoli** [comment]
@ricardogsilva you are right, django requirements were broken. Patch is ready https://github.com/geopython/pygeoapi/pull/1355

**Comment by MTachon** [comment]
Thanks for the prompt answer and the quick fix @francbartoli !

**Comment by ricardogsilva** [comment]
Just to confirm that with the recent fix provided by @francbartoli things are working smoothly again - thanks to both @francbartoli  and @MTachon

**Pull request merged**
