### PR TITLE
Add cql-json support for ES

### PR DESCRIPTION
**Pull request by francbartoli**
This pull request adds an early implementation of CQL support for the Elasticsearch provider with the CQL-JSON dialect. It supports the following type of queries:

- [X] `between` predicate query
- [X] Logical `and` query with `between` and `eq` expression
- [x] Spatial query with `bbox`

### CODE REVIEW

**Comment by jvanulde** [comment]
When is this going to be merged?

**Comment by tomkralidis** [comment]
@jvanulde we are waiting on #664 to be merged (should be very very soon) at which point we will merge this PR.

**Comment by tomkralidis** [comment]
@francbartoli as discussed, given some of the code is auto-generated by external tooling/dependencies (but not runtime dependencies), it's important to also document this (dev) workflow for updating these parts as the OGC schemas evolve over time.

**Comment by jvanulde** [comment]
🙏

**Comment by francbartoli** [comment]
@jvanulde I closed this PR given the merge was a bit messy. I'm going to open a new clean one to finally merge the stuff into master

**Comment by tomkralidis** [comment]
First pass CQL support now in master thanks to @francbartoli (for ES backends)

cc @jvanulde

**Pull request closed without merging**
