### PR TITLE
unpin dev requirements, fix flake8

### PR DESCRIPTION
**Pull request by tomkralidis**

### CODE REVIEW

**Comment by justb4** [comment]
Reason why to unpin? At least the Docker build needs to be reproducible. It is failing now on `psycopg2`:
https://cloud.docker.com/u/geopython/repository/docker/geopython/pygeoapi/builds/58b5c369-5541-4df1-b670-f51a57d87237

Ok, now see, the discussion on Gitter, but that was about `gunicorn` (?). If we add `gunicorn` to the core (in which I am neutral since it is a deploy option) then it should be pinned as well. I can imagine that we need a base version (`requirements.txt`) without all Providers. And some Providers bring their own requirements. In particular GDAL can be a pain.

**Comment by tomkralidis** [comment]
I unpinned mainly because new flake8 errors were going unnoticed given we were pinned to a specific version.  I have since opened #144.

Is there a way to test a Docker build as part of a pull request (like Travis)?

**Comment by justb4** [comment]
Can't see the relation between `flake8` and `requirements` immediately....

Yes, Travis has Docker Service support. (under `services`). We can even run the tests with Docker Image.

**Comment by tomkralidis** [comment]
The version of flake8 that was pinned in `requirements-dev.txt` did not catch flake8 errors (in this PR) that a later version of flake8 caught.

**Comment by justb4** [comment]
Aha, but in that case I would always pin to the highest version and when there is a new version pin to that. Goes for all components. I remember we had a similar issue with GHC I think. Non-reproducible builds are even considered bad practice for security reasons. We can not fully tests everything. If all would use either `virtualenv` or Docker we can always go from one stable set of versions to the next.

**Comment by tomkralidis** [comment]
We had a new version of flake8 and this went unnoticed given the pin of flake8 in master at the time. @kalxas had a good idea to have pinned versions only against stable branches.

**Pull request merged**
