### PR TITLE
- Added support for elasticsearch tiles in the mvt provider

### PR DESCRIPTION
**Pull request by doublebyte1**
# Overview
Version 8 of ES gives support to [publishing data as vector tiles](https://www.elastic.co/blog/introducing-elasticsearch-vector-tile-search-api-for-geospatial). This PR leverages that, to enable another vector tiles backend on the mvt provider.
Because ES does not provide a tilejson, I introduce the option of using a provider with no tile metadata.

# Related Issue / Discussion
https://github.com/geopython/pygeoapi/issues/970

# Additional Information
In order to use this feature, we need ES8, so I introduced another PR for using that in the examples: https://github.com/geopython/pygeoapi/pull/985
As I explain on that PR, ES needs to run on compatibility mode, or it won't work with the python client.

# Contributions and Licensing

(as per https://github.com/geopython/pygeoapi/blob/master/CONTRIBUTING.md#contributions-and-licensing)

- [x] I'd like to contribute [feature X|bugfix Y|docs|something else] to pygeoapi. I confirm that my contributions to pygeoapi will be compatible with the pygeoapi license guidelines at the time of contribution.
- [x] I have already previously agreed to the pygeoapi Contributions and Licensing Guidelines

### CODE REVIEW

**Comment by KoalaGeo** [comment]
@doublebyte1 can you add ES to the provider table & example config in https://github.com/geopython/pygeoapi/blob/master/docs/source/data-publishing/ogcapi-tiles.rst ?

**Comment by doublebyte1** [comment]
Geopython folks chat (pti-xjmc-syg - Sep 23, 2022) 1

Maybe it's an option to refactor to this architecture

**Comment by KoalaGeo** [comment]
> Geopython folks chat (pti-xjmc-syg - Sep 23, 2022) 1
> 
> Maybe it's an option to refactor to this architecture

Could also have PostGres provider like crunchy data pg_tileserv. 

Incidentally Plugging pg_tileserv into pygeoapi doesn't currently work as the metadata is not on the same path pygeoapi expects

**Comment by doublebyte1** [comment]
@KoalaGeo That's why I think it would be a good idea to detach the tile metadata from the data

**Comment by KoalaGeo** [comment]
> @KoalaGeo That's why I think it would be a good idea to detach the tile metadata from the data

👍👍

I raised https://github.com/geopython/pygeoapi/issues/820 previously and started https://github.com/geopython/pygeoapi/pull/821 (some good discussion points) but had to close as my python skills are limited

**Pull request closed without merging**
