### PR TITLE
fallback to default HTML template if custom template does not exist

### PR DESCRIPTION
**Pull request by tomkralidis**
cc also @kngai for review/comment.

This PR provides a fallback for users implementing custom templating/themes, so users wishing to only change specific templates are able to do so without carrying/maintaining the entire template tree/set.

Once @pvgenuchten and @kngai test/verify, I will update the docs accordingly.

### CODE REVIEW

**Comment by pvgenuchten** [comment]
This is a good idea, it prevents to require to duplicate all templates remotely, but only the ones with changes, which is easier to maintain

**Review by pvgenuchten — APPROVED** [review]
this works as expected, thanx!

**Comment by tomkralidis** [comment]
Thanks for the idea @pvgenuchten!

**Comment by kngai** [comment]
@tomkralidis +1. Working for me.

**Pull request merged**
