### PR TITLE
Pin pydantic dependency

### PR DESCRIPTION
**Pull request by francbartoli**
Fix https://github.com/geopython/pygeoapi/issues/1365

### CODE REVIEW

**Comment by kalxas** [comment]
pydantic 2.0 is not yet available in Debian, Ubuntu, Redhat, SUSE distros.

**Comment by francbartoli** [comment]
It is in preparation for Debian https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1052619. It is instead available for Fedora https://pkgs.org/download/python-pydantic-core

**Comment by kalxas** [comment]
Can we revert to pydantic 1.x until 2.x is generally available in the distros?

**Comment by kalxas** [comment]
Perhaps we could offer a pydantic 2.x package in UbuntuGIS once it is included in Debian.

**Comment by ricardogsilva** [comment]
@francbartoli 

We would actually need to pin pydantic with a version >=2.0.2 in  because this is the version that renamed `regex` to `pattern`, which pygeoapi is using in

https://github.com/geopython/pygeoapi/blob/2f33ff5d15367fcc14e706fb07136984a3df228a/pygeoapi/models/config.py#L37

@kalxas @tomkralidis 

I think this situation is a symptom of the overall issue that pygeoapi does not really employ a strategy to ensure reproducible installs when used standalone - we should discuss this elsewhere, but IMO a solution would be to:

1. Pin versions that are known to work in the `requirements.txt` files - these files would be used for when pygeoapi is installed in standalone mode (i.e. not as a library);
2. Do not populate the `setup.py:setup`'s `packages=` section automatically from the contents of the requirements files, but rather ensure the dependencies fed to setup.py are not pinned - this allows more freedom with dependencies when using pygeoapi as a library, which is @francbartoli 's use case here
3. Be more conservative with modifying the pygeoapi codebase to comply with newer versions of our dependencies, in order to avoid this awkward situation where pydantic v2 is now required by pygeoapi but is not available on the debian repos, which is one of our target installation methods

**Comment by tomkralidis** [comment]
Can we be conservative by making the pydantic code work with 1.x?

Having said this, we had a dependency policy meeting this past week, and there will be an RFC soon for review/comment.

**Comment by huard** [comment]
Hi, just got tripped by this. Installed pygeoapi with pip and got the `regex` is removed error. Fixed by downgrading to pydantic 1.10.

**Comment by tomkralidis** [comment]
Thanks @huard.  We will be discussing next steps on this issue next week, at which point we will propagate a release with the fix which is affecting numerous downstream applications.

**Comment by pvgenuchten** [comment]
this relates to the problem: 

```
raise TypeError("To define root models, use `pydantic.RootModel` rather than a field called '__root__'")
TypeError: To define root models, use `pydantic.RootModel` rather than a field called '__root__'
```

or is a different one?

**Pull request closed without merging**
