### PR TITLE
unfix footer (#142)

### PR DESCRIPTION
**Pull request by tomkralidis**

### CODE REVIEW

**Comment by justb4** [comment]
I struggled quite some time to get the footer "right":

* `<footer>` element from `mini.css` was not positioned ok
* explicit `div` + CSS as now looked better but still not perfect

I tested leaving out `position: fixed` as suggested here gave garbled result for `collections.html` page:

image

Tried some other variants but no good results. But then: the nesting of various CSS `<div> row/col` and `<table>` elements from `mini.css` within `pygeoapi` templates needs review and could be causing this.

**Comment by MichelGabriel** [comment]
Hi,

@pvgenuchten asked me to have a quick look at the code and I noticed that some of the problems are caused by the `max-height` in this style:
```css
table:not(.horizontal) {
    overflow: auto;
    max-height: 400px;
}
```
Although a bigger table doesn't 'listen' to this max-height, the container it is in does. So as a result the `<div class="container">` and `<main>` are also 400px high and the footer is positioned directly after these and therefore 'overwriting' the table.

**Comment by tomkralidis** [comment]
Thanks @MichelGabriel .  What would be a suggested way forward on fixing?

**Comment by MichelGabriel** [comment]
I changed some small things to make it work. Basically I made the footer fixed again by adding the class `sticky`. This PR was just removing that (sorry).

And I added some styles to `default.css`:
```css
html, body {
    background-color: #fff;
}
footer.sticky {
    position: fixed;
    width: 100%;
}
main {
    padding-bottom: 65px; /* prevent from falling under the footer */
}
table:not(.horizontal) {
    max-height: none;
}
```
And I removed the style `overflow:visible` from the table in `collections.html`. The table already had the style `overflow:auto`.

**Comment by MichelGabriel** [comment]
But if you don't want a sticky footer I can have another look.

**Comment by tomkralidis** [comment]
No problems removing a sticky footer.  Are you able to add to this PR (or feel free to open a new one)?

**Comment by tomkralidis** [comment]
@MichelGabriel sorry I meant to keep the sticky footer.  I've updated this PR to implement your comments. I think this works now?  @justb4 can you check as well?

**Comment by justb4** [comment]
Tested the branch locally: looks good now!

**Comment by justb4** [comment]
Thanks @tomkralidis and @MichelGabriel !

**Comment by justb4** [comment]
You can see the result at:
https://demo.pygeoapi.io/master/collections?f=html
(had to shift-reload for new CSS).
vs the 0.6.0 (quite old now) version:
https://demo.pygeoapi.io/stable/collections?f=html

**Pull request merged**
