### PR TITLE
[WIP] OGC API - Features (CRS and JSON-LD)

### PR DESCRIPTION
**Pull request by MTachon**
# Overview
Fix schema.org markup when serving data in data in JSON for Linking Data format. GeoCoordinates always in WGS84, and GeoShape always in WGS84 and lat/lon order, as required by the [OGC API - Features Part 2](https://docs.opengeospatial.org/is/18-058r1/18-058r1.html#_output_format_considerations) (*"...schema.org that is embedded in HTML only supports WGS 84 in the axis order latitude/longitude, so any coordinates in schema.org markup will have to be in that coordinate reference system, independent of the requested coordinate reference system."*). See also https://schema.org/GeoShape and https://schema.org/GeoCoordinates.

# Additional Information
Will need some tests to check for the correctness of the `GeoCoordinates` and `GeoShape` of the output features in JSON-LD format. PR https://github.com/geopython/pygeoapi/pull/1174 is ready to be merged, wondering if this PR should merge into https://github.com/geopython/pygeoapi/pull/1174, or into master after that https://github.com/geopython/pygeoapi/pull/1174 has been merged? @justb4 what do you think?

# Related Issue / Discussion
https://github.com/geopython/pygeoapi/pull/1174

# Contributions and Licensing

(as per https://github.com/geopython/pygeoapi/blob/master/CONTRIBUTING.md#contributions-and-licensing)

- [x] I'd like to contribute [feature X|bugfix Y|docs|something else] to pygeoapi. I confirm that my contributions to pygeoapi will be compatible with the pygeoapi license guidelines at the time of contribution.
- [x] I have already previously agreed to the pygeoapi Contributions and Licensing Guidelines

### CODE REVIEW

**Comment by justb4** [comment]
> PR https://github.com/geopython/pygeoapi/pull/1174 is ready to be merged, wondering if this PR should merge into https://github.com/geopython/pygeoapi/pull/1174, or into master after that https://github.com/geopython/pygeoapi/pull/1174 has been merged? @justb4 what do you think?

I rather see #1174 merged first. Waiting for review... It is ready and I think JSON-LD is not required for Part 2 compliance. Then we can incrementally move on.

**Comment by justb4** [comment]
@tomkralidis  Think this one needs to be re-opened. It was never merged. But now #1174 has been merged, this PR #1194 may be candidate to merge into master.

**Comment by tomkralidis** [comment]
I'm not able to re-open as there is no longer an associated branch.  Please feel feel to issue another PR.

**Comment by MTachon** [comment]
OK, will do.

**Comment by MTachon** [comment]
I opened the new PR https://github.com/geopython/pygeoapi/pull/1212 that covers the same changes.

**Pull request closed without merging**
